# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# tflint-ignore: terraform_unused_declarations
variable "env" {
  description = "環境のプレフィックス"
  type        = string
}

# tflint-ignore: terraform_unused_declarations
variable "system" {
  description = "システム名称(-区切り)"
  type        = string
}

variable "ec2_key_pair_name" {
  description = "EC2 Key Pair Name"
  type        = string
  
}
locals {
  # tflint-ignore: terraform_unused_declarations
  prefix = "${var.system}-${var.env}"
  # tflint-ignore: terraform_unused_declarations
  tags = {
    "Terraform"   = "true"
    "Environment" = var.env
    "System"      = var.system
  }
}
